#!/bin/sh
#
# @name DJI F550 SITL
#
# @type Hexacopter x
#
# @maintainer Vojtech Spurny <vojtech.spurny@fel.cvut.cz>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}

param set-default SIM_GZ_EN 1

param set-default MAV_TYPE 13

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 6800
param set-default BAT1_V_EMPTY 3.6
param set-default BAT1_V_CHARGED 4.2

# NOTES:

# The CA_ROTOR* parameters replaced the PX4 mixers
# It is now simpler to configure new models, but keep in mind these points:

## 1) CA_ROTOR*_P* params use the FRD coordinates (X+ is in front of the center of mass (CoM), Y+ is right of CoM, Z+ is below CoM)
## The index order does NOT match the jinja model

## 2) CA_ROTOR*_CT is thrust output scaling - multiplier of the output SIGNAL
## It is NOT the motor constant from the jinja model

## 3) CA_ROTOR*_KM is the moment ratio between roll/pitch and yaw
## It should match the moment constant from the jinja model

param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 0.275
param set-default CA_ROTOR0_PZ -0.0115
param set-default CA_ROTOR0_CT 1.0
param set-default CA_ROTOR0_KM -0.06

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -0.275
param set-default CA_ROTOR1_PZ -0.0115
param set-default CA_ROTOR1_CT 1.0
param set-default CA_ROTOR1_KM 0.06

param set-default CA_ROTOR2_PX 0.23816
param set-default CA_ROTOR2_PY -0.1375
param set-default CA_ROTOR2_PZ -0.0115
param set-default CA_ROTOR2_CT 1.0
param set-default CA_ROTOR2_KM -0.06

param set-default CA_ROTOR3_PX -0.23816
param set-default CA_ROTOR3_PY 0.1375
param set-default CA_ROTOR3_PZ -0.0115
param set-default CA_ROTOR3_CT 1.0
param set-default CA_ROTOR3_KM 0.06

param set-default CA_ROTOR4_PX 0.23816
param set-default CA_ROTOR4_PY 0.1375
param set-default CA_ROTOR4_PZ -0.0115
param set-default CA_ROTOR4_CT 1.0
param set-default CA_ROTOR4_KM 0.06

param set-default CA_ROTOR5_PX -0.23816
param set-default CA_ROTOR5_PY -0.1375
param set-default CA_ROTOR5_PZ -0.0115
param set-default CA_ROTOR5_CT 1.0
param set-default CA_ROTOR5_KM -0.06

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000
